	/* Application */
	FWK_ID_CLOUD = FWK_ID_APP_START,
#ifdef CONFIG_SENSOR_TASK
	FWK_ID_SENSOR_TASK,
#endif
#ifdef CONFIG_COAP_FOTA
	FWK_ID_COAP_FOTA_TASK,
#endif
#ifdef CONFIG_HTTP_FOTA
	FWK_ID_HTTP_FOTA_TASK,
#endif
